### ISSUE TITLE
Cannot dismiss an article.

### ISSUE THREAD

**Issue by Giger22** [exequtic/apdatifier#12]
Hello, I keep dismissing a new [article](https://archlinux.org/news/increasing-the-default-vmmax_map_count-value/) but after every login or a startup it shows up again.

**Comment by exequtic** [comment]
Hi! Could you please open the file `~/.config/plasma-org.kde.plasma.desktop-appletsrc` and find the line starting with `lastNews=`? Does that line exist and what is the value of `dismissed`?

**Comment by Giger22** [comment]
lastNews={"article":"The xz package has been backdoored","date":"2024-03-29","link":"https://archlinux.org/news/the-xz-package-has-been-backdoored","dismissed":true}
So it looks like it does not add a new article.

**Comment by exequtic** [comment]
I don't yet understand why this problem is occurring because I can't reproduce it myself.
You can try reinstall plasmoid. This should remove plasmoid and its settings and install it with the latest commit.

`curl -fsSL https://raw.githubusercontent.com/exequtic/apdatifier/main/package/contents/tools/tools.sh | sh -s install`
