### ISSUE TITLE
Widget causing Plasmashell to crash sometimes

### ISSUE THREAD

**Issue by DarkXero-dev** [exequtic/apdatifier#34]
Hey my friend

I dunno why, but when widget initiates an update check sometimes plasmashell decides to crash on both X11 and Wayland. I sent report to KDE devs they just said not related to Plasma. I am unsure if it's actually your widget causing it or not.. If not disregard.

I don't have any other widgets running only Apdatifier.

**Comment by exequtic** [comment]
Hi. Need to find out if this widget is really causing the crash. Try disabling the widget or turning off the auto-check interval to see if the crashes persist. Were there any crashes before, or did they start only after the latest Plasma update?

**Comment by Shehata-git** [comment]
Can you check the "Journald Browser" or "KSystemLog" provided in kde?
Maybe you can get a bit more context on what happened beforehand for a more helpful outcome.

**Comment by QuarkZ26** [comment]
I have to say, I feel like there's definitely a correlation. Twice now, I have observed with my own eye Plasma crashing/restarting just as Apdatifier started an update check.


![image](https://github.com/user-attachments/assets/5529b624-704d-4373-9c3a-f2e432e28a03)

You can see here that it crashes just about once a day. I've since then paused Apdatifier and only use manual check and there hasn't been a crash since the 16th.

Now I can't say whether it's a Plasma problem or the widget, I really only use this one (that isn't a default Plasma one), but I do think something is tied to this.

**Comment by DarkXero-dev** [comment]
There you go. Sorry was very busy with my projects and potential war here. But yes I can confirm the behavior. 

It happened on my laptop during Kernel update and rebuild which in turn resulted in unbootable system that I fixed via chroot. 

Issue has been there since Plasma 6.1.x so no clue.

**Comment by QuarkZ26** [comment]
To be clear, it never happened to me during an update, the only times I've been able to see this is when the widget is setup to auto check and starts an actual check, as in, it starts and Plasma immediately crashes and restarts. 

It never really created any issues for me beyond that, but seeing it happens twice as soon as the auto check started made me suspicious, although I'm not sure how I could confirm the times I'm not in front of the machine since I don't believe there's any log for the widget? Something that would show each time the auto check happens.

**Comment by DarkXero-dev** [comment]
For me it almost always happens an update initiated through widget. It's really annoying. I can't live without it so I put up with it. 

Requires a lot of investigation which I have no time for right now coz a war is about to blow here gotta find shelter soon.

**Comment by exequtic** [comment]
I still can’t reproduce the crash when checking for updates, which makes it difficult to troubleshoot blindly.
However, I was able to reproduce a crash during a system upgrade, and that led me to make some experimental changes. With these changes, the crash no longer occurs during upgrades. It’s possible that they might also prevent crashes during update checks for you.
Please test the latest commit and let me know the results.

```
git clone https://github.com/exequtic/apdatifier.git
kpackagetool6 -t Plasma/Applet -u apdatifier/package
```

Make sure to restart plasmashell or Log Out after this.

**Comment by DarkXero-dev** [comment]
No crashes anymore but wrapper is broke

![wrapper](https://i.imgur.com/AUbDXPl.png)

also Terminal

![term](https://i.imgur.com/ysGiMd8.png)

**Comment by exequtic** [comment]
I'll fix this a bit later.
It happens because the file `$HOME/.config/apdatifier/news.json` is missing. Check the news or manually create the file with empty [] inside and restart plasmashell.

**Comment by DarkXero-dev** [comment]
I just did and now get this

![Screenshot_20241117_105721](https://github.com/user-attachments/assets/5fb8a140-a14a-4611-a6f4-aa71a55e5584)

**Comment by DarkXero-dev** [comment]
@exequtic 

Excellent, will update the XeroLinux rice soon.. Maybe bump version to 2.9.0 ?

**Comment by exequtic** [comment]
I’m always worried about releasing a new version - something always ends up breaking that I didn’t catch. I’ve made significant under-the-hood changes since the last version, so I need to make sure everything works properly. Most likely, I’ll release 2.9 in the middle of next week.

**Comment by DarkXero-dev** [comment]
@exequtic 

I agree, better safe than sorry. It's always a good precaution. Well, will wait until you do. No sense in pushing git version to the masses as you so well pointed out ;)
